export const eduInstitutesData = [
  {
    category: 'Oliy taʼlim muassasalari',
    data: [
      {
        id: 1,
        name: 'Namangan davlat universiteti',
        address: 'Namangan shahri, Boburko‘chasi 161-uy',
        rector: 'Turgunov Sobitxon To‘lqinboyevich',
      },
      {
        id: 2,
        name: 'Namangan muhandislik-qurilish instituti',
        address:
          'Yangi Namangan tumani, Mingturkon MFY, Muloqot ko‘chasi 12-uy',
        rector: 'Ergashev Sharifboy Tulanovich',
      },
      {
        id: 3,
        name: 'Namangan muhandislik-texnologiya instituti',
        address: "Davlatabod tumani, Kosonsoy ko'chasi 7-uy",
        rector: 'Mamatkarimov Odiljon Oxundadaevich',
      },
      {
        id: 4,
        name: 'Namangan davlat pedagogika instituti',
        address: "Namangan shahri Sharq tongi MFY, Uychi ko'chasi 316-uy",
        rector: 'Xusanov Bahodir Ergashevich',
      },
      {
        id: 5,
        name: 'Isxoqxon Ibrat nomidagi Namangan davlat chet tillari instituti',
        address: "To'raqo'rg'on tumani, Yangiobod MFY, Saodat ko'chasi 28-uy",
        rector: "Karimov Rivojiddin G'ulomjonovich",
      },
      {
        id: 6,
        name: "Namangan to'qimachilik sanoat instituti",
        address:
          "Namangan shahar Davlatobod tumani Gulobod MFY janubiy aylanma yo'li ko'chasi 17-uy",
        rector: 'Xoliqov Qurbonali Madaminovich',
      },
      {
        id: 7,
        name: 'Toshkent Kimyo Xalqaro Universiteti Namangan filiali',
        address: "Namangan shahri Chortoq ko'chasi 75a-uy",
        rector: "Rasulov To'lqin Sattarovich",
      },
      {
        id: 8,
        name: 'Turan International University',
        address: "Namangan shahri, Qodir Mamarasulov ko'chasi 10-uy",
        rector: 'Gulnara Jagiparovna Nurmuxanova',
      },
      {
        id: 9,
        name: 'Impuls Medical Institute Impuls BSR Ltd',
        address:
          "Namangan shahri G'ishtko'prik MFY, K.Otamirzayev ko'chasi 1-uy",
        rector: "Xolmirzayev Orifjon No'monjon o'g'li",
      },
      {
        id: 10,
        name: 'University of Business and Science',
        address: "Namangan shahri Zarbdor MFY, Beshkapa ko'chasi 111-uy",
        rector: 'Boymirzayev Karimjon Mirzahmedovich',
      },
      {
        id: 11,
        name: 'Toshkent iqtisodiyot va tehnologiyalar universiteti',
        address:
          "Namangan shahri Oromgoh MFY, Shimoliy aylanma ko'chasi, 16-uy",
        rector: 'Ergashev Sharifboy Tulanovich',
      },
    ],
  },
  {
    category: 'professional taʼlim muassasalari',
    data: [
      {
        id: 1,
        name: 'Namangan shahar ',
        address: 'Ozod MFY ',
        rector: 'Namangan shahar 1-son kasb-hunar maktabi ',
      },
      {
        id: 2,
        name: 'Namangan shahar',
        address: 'Dashtbogʻ MFY',
        rector: 'Namangan shahar 2-son kasb-hunar maktabi',
      },
      {
        id: 3,
        name: 'Namangan shahar',
        address: 'Oydinkoʻl MFY',
        rector: 'Namangan pedagogika kolleji',
      },
      {
        id: 4,
        name: 'Davlatobod tumani',
        address: 'Porloq MFY',
        rector: 'Namangan olimpiya zaxiralari kolleji',
      },
      {
        id: 5,
        name: 'Namangan shahar',
        address: 'Nugaykurgon',
        rector:
          'Namangan Abu Ali ibn Sino nomidagi Jamoat salomatligi texnikumi',
      },
      {
        id: 6,
        name: 'Yangi Namangan tumani',
        address: 'Sihatgoh MFY',
        rector:
          '2-son Namangan Abu Ali ibn Sino nomidagi Jamoat salomatligi texnikumi	',
      },
      {
        id: 7,
        name: 'Namangan shahar',
        address: 'Gulbogʻ MFY',
        rector: 'Namangan xizmat koʻrsatish va servis texnikumi',
      },
      {
        id: 8,
        name: 'Davlatobod tumani ',
        address: 'Gulobod MFY',
        rector: 'Namangan tadbirkorlikni tashkil etish texnikumi',
      },
      {
        id: 9,
        name: 'Namangan shahar',
        address: 'Ravnaq MFY',
        rector: 'Namangan viloyat yuridik texnikumi',
      },
      {
        id: 10,
        name: 'Namangan shahar',
        address: 'Baynalminal MFY',
        rector: 'Namangan arxitektura va qurilish texnikumi',
      },
      {
        id: 11,
        name: 'Kosonsoy tuman',
        address: 'Gulobod MFY ',
        rector: 'Kosonsoy tuman 1-son kasb-hunar maktabi 	',
      },
      {
        id: 12,
        name: 'Kosonsoy tumani	',
        address: 'Navbahor MFY 	',
        rector: 'Kosonsoy tuman 2-son kasb-hunar maktabi	',
      },
      {
        id: 13,
        name: 'Kosonsoy tumani	',
        address: 'Soy boʻyi MFY	',
        rector: 'Kosonsoy tuman 3-son kasb-hunar maktabi	',
      },
      {
        id: 14,
        name: 'Kosonsoy tumani    ',
        address: 'Gulobod MFY',
        rector: 'Kosonsoy pedagogika kolleji ',
      },
      {
        id: 15,
        name: 'Kosonsoy tuman',
        address: 'Chorbogʻ MFY',
        rector: 'Kosonsoy sanoatda axborot texnologiyalari texnikumi',
      },
      {
        id: 16,
        name: 'Mingbuloq tuman',
        address: 'Xayitobod MFY ',
        rector: 'Mingbuloq tuman 1-son kasb-hunar maktabi	',
      },
      {
        id: 17,
        name: 'Mingbuloq tuman',
        address: 'Qolgandaryo MFY',
        rector: 'Mingbuloq tuman 2-son kasb-hunar maktabi',
      },
      {
        id: 18,
        name: 'Mingbuloq tumani',
        address: 'Mustaqillik MFY',
        rector: 'Mingbuloq suv xoʻjaligi va melioratsiya kolleji	',
      },
      {
        id: 19,
        name: 'Mingbuloq tumani',
        address: 'Bozorboshi MFY',
        rector: 'Mingbuloq pedagogika kolleji',
      },
      {
        id: 20,
        name: 'Mingbuloq tuman',
        address: 'Oʻzgarish MFY',
        rector: 'Mingbuloq yengil sanoat texnikumi',
      },
      {
        id: 21,
        name: 'Namangan tumani',
        address: 'Shoʻrqoʻrgʻon MFY ',
        rector: 'Namangan tuman 1-son kasb-hunar maktabi ',
      },
      {
        id: 22,
        name: 'Namangan tuman',
        address: 'Anjirzor MFY',
        rector: 'Namangan tuman 2-son kasb-hunar maktabi',
      },
      {
        id: 23,
        name: 'Namangan tumani',
        address: 'Katta Toshbuloq mfy',
        rector: 'Namangan tuman pedagogika kolleji',
      },
      {
        id: 24,
        name: 'Namangan tuman',
        address: 'Navruz MFY ',
        rector: 'Namangan sanoat va iqtisodiyot texnikumi',
      },
      {
        id: 25,
        name: 'Namangan tuman ',
        address: 'Qumqoʻrgʻon MFY ',
        rector: 'Namangan sharq tillari va xizmat koʻrsatish texnikumi',
      },
      {
        id: 26,
        name: 'Norin tuman',
        address: 'Xaqqulobod shaxri',
        rector: 'Norin tuman 1-son kasb-hunar maktabi',
      },
      {
        id: 27,
        name: 'Norin tuman',
        address: 'Changitma MFY',
        rector: 'Changitma MFY',
      },
      {
        id: 28,
        name: 'Norin tumani',
        address: 'Margʻizor mfy',
        rector: 'Norin tuman pedagogika kolleji',
      },
      {
        id: 29,
        name: 'Xakkulobod shaxar',
        address: 'Yettikashka MFY',
        rector: 'Norin Abu Ali ibn Sino nomidagi Jamoat salomatligi texnikumi',
      },
      {
        id: 30,
        name: 'Norin tumani',
        address: 'Yuqori Choʻja MFY',
        rector: 'Norin maishiy xizmat koʻrsatish va servis texnikumi',
      },
      {
        id: 31,
        name: 'Pop tuman	',
        address: 'Toshqoʻrgʻon MFY',
        rector: 'Pop tuman 1-son kasb-hunar maktabi',
      },
      {
        id: 32,
        name: 'Pop tumani	',
        address: 'Obod MFY',
        rector: 'Pop tuman 2-son kasb-hunar maktabi	',
      },
      {
        id: 33,
        name: 'Pop tuman	',
        address: 'Istiqbol MFY',
        rector: 'Pop tuman 3-son kasb-hunar maktabi',
      },
      {
        id: 34,
        name: 'Pop tumani	',
        address: 'Chigʻanoq MFY',
        rector: 'Pop pedagogika kolleji',
      },
      {
        id: 35,
        name: 'Pop tumani	',
        address: 'Paxtakor MFY',
        rector: 'Pop Abu Ali ibn Sino nomidagi Jamoat salomatligi texnikumi',
      },
      {
        id: 36,
        name: 'Toʻraqoʻrgʻon tumani',
        address: 'Toshkent MFY ',
        rector: 'Toʻraqoʻrgʻon tuman 1-son kasb-hunar maktabi',
      },
      {
        id: 37,
        name: 'Toʻraqoʻrgʻon tuman',
        address: 'Past Naymancha MFY ',
        rector: 'Toʻraqoʻrgʻon tuman 2-son kasb-hunar maktabi',
      },
      {
        id: 38,
        name: 'Toʻraqoʻrgʻon tumani',
        address: 'Oʻzbekiston MFY',
        rector: 'Toʻraqoʻrgʻon pedagogika kolleji',
      },
      {
        id: 39,
        name: 'Toʻraqoʻrgʻon tumani',
        address: 'Yortepa MFY',
        rector: 'Toʻraqoʻrgʻon agrosanoat texnikumi',
      },
      {
        id: 40,
        name: 'Toʻraqoʻrgʻon tuman	',
        address: 'Chust koʻprik',
        rector: 'Toʻraqoʻrgʻon agrotexnologiyalar texnikumi',
      },
      {
        id: 41,
        name: '	Uychi tumani 	',
        address: 'Soku MFY ',
        rector: 'Uychi tuman 1-son kasb-hunar maktabi',
      },
      {
        id: 42,
        name: 'Uychi tumani',
        address: 'Shifokor MFY ',
        rector: 'Uychi tuman 2-son kasb-hunar maktabi',
      },
      {
        id: 43,
        name: 'Uychi tumani',
        address: 'Gʻayrat MFY',
        rector: 'Uychi tumani pedagogika kolleji',
      },
      {
        id: 44,
        name: 'Uychi tumani',
        address: 'Dehqon MFY',
        rector: 'Namangan sanoat texnikumi',
      },
      {
        id: 45,
        name: 'Uychi tumani	',
        address: 'Mustaqillik MFY ',
        rector: 'Uychi jismoniy tarbiya va sport texnikumi',
      },
      {
        id: 46,
        name: 'Uchqoʻrgʻon tumani',
        address: 'Yoshlik MFY ',
        rector: 'Uchqoʻrgʻon tuman 1-son kasb-hunar maktabi',
      },
      {
        id: 47,
        name: 'Uchqoʻrgʻon tumani',
        address: 'Dexqonobod MFY ',
        rector: 'Uchqoʻrgʻon tuman 2-son kasb-hunar maktabi',
      },
      {
        id: 48,
        name: 'Uchqoʻrgʻon tuman',
        address: 'Koʻprikboshi MFY 	',
        rector: 'Uchqoʻrgʻon pedagogika kolleji',
      },
      {
        id: 49,
        name: 'Uchqoʻrgʻon tumani ',
        address: 'Qoʻgʻay MFY ',
        rector: 'Uchqoʻrgʻon sanoat-texnologiyalari texnikumi',
      },
      {
        id: 50,
        name: 'Chortoq shahar ',
        address: 'Namangan MFY',
        rector: 'Chortoq tuman 1-son kasb-hunar maktabi',
      },
      {
        id: 51,
        name: 'Chortoq tumani',
        address: 'Bogʻ MFY ',
        rector: 'Chortoq tuman 2-son kasb-hunar maktabi',
      },
      {
        id: 52,
        name: 'Chortoq shahar ',
        address: 'A.Navoiy MFY ',
        rector:
          '	Chortoq Abu Ali ibn Sino nomidagi Jamoat salomatligi texnikumi',
      },
      {
        id: 53,
        name: '	Chust tuman	',
        address: 'Birlik MFY',
        rector: 'Chust tuman 1-son kasb-hunar maktabi',
      },
      {
        id: 54,
        name: 'Chust shahar',
        address: 'Guliston MFY ',
        rector: 'Chust tuman 2-son kasb-hunar maktabi',
      },
      {
        id: 55,
        name: 'Chust tuman	',
        address: 'Baymoq MFY ',
        rector: '	Chust tuman 3-son kasb-hunar maktabi',
      },
      {
        id: 56,
        name: '	Chust tumani 	',
        address: 'Mustaqillik MFY 	',
        rector: 'Chust pedagogika kolleji',
      },
      {
        id: 57,
        name: 'Chust tumani	',
        address: 'Doʻstlik MFY',
        rector: 'Chust Abu Ali ibn Sino nomidagi Jamoat salomatligi texnikumi',
      },
      {
        id: 58,
        name: '	Yangiqoʻrgʻon tuman	',
        address: 'Beshbuloq MFY ',
        rector: 'Yangiqoʻrgʻon tuman 1-son kasb-hunar maktabi',
      },
      {
        id: 59,
        name: 'Yangiqoʻrgʻon tuman',
        address: 'Madaniyat MFY ',
        rector: 'Yangiqoʻrgʻon tuman 2-son kasb-hunar maktabi	',
      },
      {
        id: 60,
        name: 'Yangiqoʻrgʻon tumani',
        address: 'Buloq boshi MFY',
        rector: 'Yangiqoʻrgʻon pedagogika kolleji',
      },
      {
        id: 61,
        name: 'Yangiqoʻrgʻon tuman',
        address: 'Nurafshon MFY',
        rector: 'Yangiqoʻrgʻon axborot texnologiyalari texnikumi	',
      },
    ],
  },
];
