name: Branch Name Checker

on:
  push:
    branches:
      - '*'

jobs:
  branch-name-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Branch Name
        run: |
          echo "Checking branch name: ${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" != feature/* && \
                "${{ github.ref_name }}" != hotfix/* && \
                "${{ github.ref_name }}" != refactor/* && \
                "${{ github.ref_name }}" != chore/* && \
                "${{ github.ref_name }}" != develop && \
                "${{ github.ref_name }}" != main && \
                "${{ github.ref_name }}" != release/* ]]; then
            echo "❌ Branch name does not follow conventions. Valid naming conventions are:"
            echo "  - feature/* (New features)"
            echo "  - hotfix/* (Urgent bug fixes)"
            echo "  - refactor/* (Code restructuring)"
            echo "  - chore/* (Minor maintenance changes)"
            echo "  - develop (Ongoing development branch)"
            echo "  - main (Production-ready branch)"
            echo "  - release/* (Version release branches)"
            exit 1
          else
            echo "✅ Branch name is valid."
          fi
